title: Rommane LG
logo: /assets/img/logo-master.png
description: 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
jekyll_compose:
  default_front_matter:
    posts:
      tags: TODO
plugins:
  - jekyll-mentions
  - jekyll-github-metadata
  - jemoji
